name: "medaka"
description: Polish genome assemblies using Oxford Nanopore reads
keywords:
  - polishing
  - assembly
  - nanopore
  - ont
  - consensus
tools:
  - medaka:
      description: "Sequence correction provided by ONT Research"
      homepage: "https://github.com/nanoporetech/medaka"
      documentation: "https://github.com/nanoporetech/medaka"
      tool_dev_url: "https://github.com/nanoporetech/medaka"
      licence: ["MPL-2.0"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample1' ]
  - reads:
      type: file
      description: FASTQ file with nanopore reads
      pattern: "*.{fastq.gz,fq.gz}"
  - assembly:
      type: file
      description: Draft assembly to polish
      pattern: "*.{fa,fasta,fna}"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'sample1' ]
  - polished_fasta:
      type: file
      description: Polished assembly FASTA file
      pattern: "*_polished.fasta"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@gene2dis"
maintainers:
  - "@gene2dis"
