import os
import pandas as pd
import argparse
import json

def get_sample_names(input_folder):
    """
    Function to read the folder generated by MGAP and get the sample ids.
    Skips the run-level (non-sample) output directories.
    """
    non_sample_dirs = {"pipeline_info", "gtdbtk", "multiqc"}
    sample_names = []
    for folder in os.listdir(input_folder):
        if folder in non_sample_dirs:
            continue
        if not os.path.isdir(os.path.join(input_folder, folder)):
            continue
        sample_names.append(folder)

    return sample_names

def parse_read_processing(input_folder, sample):
    """
    Function to parse the read processing output of MGAP, including
    FASTP, Bracken, and MASH results
    """
    # Process the fastp (Illumina) or fastplong (ONT) json
    read_jsons = [
        input_folder + "/" + sample + "/read_processing/fastp/" + sample + ".fastp.json",
        input_folder + "/" + sample + "/read_processing/fastplong/" + sample + ".fastplong.json",
    ]

    before_reads = after_reads = before_bases = after_bases = 0
    for read_json in read_jsons:
        try:
            fastp_json = json.load(open(read_json))
            before_reads = fastp_json["summary"]["before_filtering"]["total_reads"]
            after_reads = fastp_json["summary"]["after_filtering"]["total_reads"]
            before_bases = fastp_json["summary"]["before_filtering"]["total_bases"]
            after_bases = fastp_json["summary"]["after_filtering"]["total_bases"]
            break
        except (FileNotFoundError, KeyError, json.JSONDecodeError):
            # Missing (e.g. contig mode) or malformed json: keep zeros / try next
            continue

    fastp_out = pd.DataFrame(
        {"reads_before": before_reads,
         "reads_after": after_reads,
         "bases_before": before_bases,
         "bases_after": after_bases},
         index = [sample]
    )

    # Process the mash results
    mash_stats = []

    try:
        with open(input_folder + "/" + sample + "/read_processing/mash/" + sample + ".mash_stats") as mash_file:
            for line in mash_file:
                if line.startswith("Estimated genome size"):
                    mash_stats.append(line.strip().split()[-1])
                if line.startswith("Estimated coverage"):
                    mash_stats.append(line.strip().split()[-1])
    except FileNotFoundError:
        pass

    # Guard against missing/truncated mash output (e.g. contig mode, or a
    # mash version with different wording) instead of crashing on indexing
    while len(mash_stats) < 2:
        mash_stats.append(0)

    mash_out = pd.DataFrame(
        {"genome_size": mash_stats[0],
         "coverage": mash_stats[1]},
         index = [sample]
    )

    # Process the bracken results
    try:
        bracken_out_raw = pd.read_csv(input_folder + "/" + sample + "/read_processing/bracken/" + sample + ".tsv", sep="\t")
        bracken_out_raw["sample"] = sample
        bracken_out_raw = bracken_out_raw.set_index("sample")
        bracken_out_filtered = bracken_out_raw[bracken_out_raw["fraction_total_reads"] > 0.01]

    except FileNotFoundError:
        # If the bracken stats file is not found, set the values to 0
        bracken_out_filtered = pd.DataFrame()


    return fastp_out, mash_out, bracken_out_filtered

def parse_assembly_qc(input_folder, sample):
    """
    Function to parse the assembly QC results of MGAP. Missing metrics
    (or a missing/truncated QUAST report) yield "NA" values instead of
    aborting the whole consolidation.
    """
    metric_columns = {
        "# contigs (>= 0 bp)": "contigs_0",
        "# contigs (>= 10000 bp)": "contigs_10k",
        "# contigs (>= 50000 bp)": "contigs_50k",
        "# contigs": "contigs_total",
        "Total length (>= 0 bp)": "length_0",
        "Total length (>= 10000 bp)": "length_10k",
        "Total length (>= 50000 bp)": "length_50k",
        "Total length": "length_total",
        "Largest contig": "largest_contig",
        "GC (%)": "gc",
        "N50": "n50",
    }

    metrics = {}
    try:
        with open(input_folder + "/" + sample + "/qc/quast/" + sample + ".tsv") as quast_tsv:
            for line in quast_tsv:
                elements = line.strip().split("\t")
                if len(elements) > 1 and elements[0] in metric_columns:
                    metrics[metric_columns[elements[0]]] = elements[1]
    except FileNotFoundError:
        print("Warning: no QUAST report for sample " + sample)

    qc_out = pd.DataFrame(
        {column: metrics.get(column, "NA") for column in metric_columns.values()},
        index=[sample],
    )

    return qc_out

def parse_checkm2(checkm2_file, sample):
    """
    Function to parse the checkm2 results
    """
    cm2_file = pd.read_csv(checkm2_file, sep="\t")
    cm2_file["sample"] = sample
    cm2_file = cm2_file.set_index("sample")
    cm2_file.drop(columns = ["Name"], inplace=True)

    return cm2_file

def parse_mlst(mlst_file, sample):
    """
    Function to parse the MLST results. It has to be able to handle
    a variable number of columns
    """
    mlst_parsed = None
    with open(mlst_file) as mlst:
        for line in mlst:
            line = line.strip().split("\t")
            species_mlst = line[1]
            st = line[2]
            alleles = line[3:]

            mlst_dict = {
                "species": species_mlst,
                "ST": st
            }

            for allele in alleles:
                name = "gene_" + str(alleles.index(allele) + 1)
                mlst_dict[name] = allele


            mlst_parsed = pd.DataFrame(
                mlst_dict,
                index = [sample]
            )
    return mlst_parsed

def parse_bakta(bakta_result, sample):
    """
    Function to parse the bakta results
    """
    bakta_parsed = pd.read_csv(bakta_result, sep="\t",
                               header=None, skiprows=3,
                               names=["contig", "type", "start", "stop", "strand",
                                      "locus tag", "gene", "product", "dbxrefs"])
    bakta_parsed["sample"] = sample
    bakta_parsed = bakta_parsed.set_index("sample")

    return bakta_parsed

def parse_amrfinder(amrfinder_result, sample):
    """
    Function to parse the amrfinder results
    """
    amrfinder_parsed = pd.read_csv(amrfinder_result, sep="\t")
    amrfinder_parsed["sample"] = sample
    amrfinder_parsed = amrfinder_parsed.set_index("sample")

    return amrfinder_parsed

def parse_genomad(genomad_result, sample):
    """
    Function to parse the genomad results
    """
    genomad_parsed = pd.read_csv(genomad_result, sep="\t")
    genomad_parsed["sample"] = sample
    genomad_parsed = genomad_parsed.set_index("sample")

    return genomad_parsed


def parse_annotation(input_folder, sample):
    """
    Function to parse the annotation results of MGAP. Steps that did not
    run (their database was not provided) or produced no file yield None.
    """

    def parse_if_present(parser, path):
        try:
            return parser(path, sample)
        except FileNotFoundError:
            return None
        except (IndexError, KeyError, pd.errors.EmptyDataError):
            print("Warning: could not parse " + path + " - skipping")
            return None

    annotation_dir = input_folder + "/" + sample + "/annotation/"

    checkm2_out = parse_if_present(parse_checkm2, annotation_dir + "checkm2/" + sample + ".quality_report.tsv")
    mlst_out = parse_if_present(parse_mlst, annotation_dir + "mlst/" + sample + ".tsv")
    bakta_out = parse_if_present(parse_bakta, annotation_dir + "bakta/" + sample + ".tsv")
    amrfinder_out = parse_if_present(parse_amrfinder, annotation_dir + "amrfinder/" + sample + ".tsv")
    genomad_virus_out = parse_if_present(parse_genomad, annotation_dir + "genomad/" + sample + "_virus_summary.tsv")
    genomad_plasmid_out = parse_if_present(parse_genomad, annotation_dir + "genomad/" + sample + "_plasmid_summary.tsv")

    return checkm2_out, mlst_out, bakta_out, amrfinder_out, genomad_virus_out, genomad_plasmid_out

def parse_kleborate(input_folder, sample):
    """
    Function to parse the kleborate results
    """
    kleborate_out = pd.read_csv(input_folder + "/" + sample + "/annotation/kleborate/" + sample + ".results.txt",
                                sep="\t")
    kleborate_out.rename(columns={"strain": "sample"}, inplace=True)
    kleborate_out = kleborate_out.set_index("sample")

    return kleborate_out

def parse_sccmec(input_folder, sample):
    """
    Function to parse the sccmec results
    """
    sccmec_out = pd.read_csv(input_folder + "/" + sample + "/annotation/sccmec/" + sample + ".tsv",
                             sep="\t")
    sccmec_out = sccmec_out.set_index("sample")

    return sccmec_out


# Run main script
if __name__ == "__main__":
    program_description = "Script to process the output of the MGAP pipeline, \
        and consolidate into different tables for visualization"

    parser = argparse.ArgumentParser(description=program_description)

    # Arguments
    parser.add_argument("-i", "--input_folder",
                        help="Path to the folder containing the MGAP output",
                        required=True, type=str)
    parser.add_argument("-o", "--output_folder", help="Output folder for the tables",
                        required=True, type=str)
    parser.add_argument("-r", "--replace", help="Replace existing samples",
                        required=True, type=str)

    args = parser.parse_args()

    # Create output folder
    if not os.path.exists(args.output_folder):
        os.makedirs(args.output_folder)

    # Read the input folder
    ## Get samples names
    sample_names = get_sample_names(args.input_folder)

    # Parse the read processing results
    fastp_results = []
    mash_results = []
    bracken_results = []

    for sample in sample_names:
        fastp, mash, bracken = parse_read_processing(args.input_folder, sample)
        fastp_results.append(fastp)
        mash_results.append(mash)
        bracken_results.append(bracken)

    df_fastp = pd.concat(fastp_results)
    df_mash = pd.concat(mash_results)
    df_bracken = pd.concat(bracken_results)

    # Parse the assembly results
    qc_assembly = []
    for sample in sample_names:
        qc = parse_assembly_qc(args.input_folder, sample)
        qc_assembly.append(qc)

    df_qc = pd.concat(qc_assembly)

    # Parse the annotation results
    checkm2_results = []
    mlst_results = []
    bakta_results = []
    amrfinder_results = []
    genomad_virus_results = []
    genomad_plasmid_results = []
    kleborate_results = []
    sccmec_results = []

    for sample in sample_names:
        checkm2, mlst, bakta, amrfinder, genomad_virus, genomad_plasmid = parse_annotation(args.input_folder, sample)
        if checkm2 is not None:
            checkm2_results.append(checkm2)
        if mlst is not None:
            mlst_results.append(mlst)
        if bakta is not None:
            bakta_results.append(bakta)
        if amrfinder is not None:
            amrfinder_results.append(amrfinder)
        if genomad_virus is not None:
            genomad_virus_results.append(genomad_virus)
        if genomad_plasmid is not None:
            genomad_plasmid_results.append(genomad_plasmid)

        # Specific annotations
        if os.path.exists(args.input_folder + "/" + sample + "/annotation/kleborate"):
            kleborate_results.append(parse_kleborate(args.input_folder, sample))

        if os.path.exists(args.input_folder + "/" + sample + "/annotation/sccmec"):
            sccmec_results.append(parse_sccmec(args.input_folder, sample))

    def concat_or_none(frames):
        return pd.concat(frames) if frames else None

    output_tables = {
        "fastp_results.tsv": df_fastp,
        "mash_results.tsv": df_mash,
        "bracken_results.tsv": df_bracken,
        "qc_assembly.tsv": df_qc,
        "checkm2_results.tsv": concat_or_none(checkm2_results),
        "mlst_results.tsv": concat_or_none(mlst_results),
        "bakta_results.tsv": concat_or_none(bakta_results),
        "amrfinder_results.tsv": concat_or_none(amrfinder_results),
        "genomad_virus_results.tsv": concat_or_none(genomad_virus_results),
        "genomad_plasmid_results.tsv": concat_or_none(genomad_plasmid_results),
        "kleborate_results.tsv": concat_or_none(kleborate_results),
        "sccmec_results.tsv": concat_or_none(sccmec_results),
    }

    # Write the results
    if args.replace == "Yes":
        for filename, table in output_tables.items():
            if table is not None:
                table.to_csv(args.output_folder + "/" + filename, sep="\t", index_label="sample")

    elif args.replace == "No":
        for filename, table in output_tables.items():
            if table is not None:
                table.to_csv(args.output_folder + "/" + filename, sep="\t", index_label="sample", header=False, mode="a")

    else:
        print("Error: replace argument must be Yes or No")
