name: sccmec
description: Types SCCmec cassettes in Staphylococcus aureus assemblies using camlhmp-based BLAST.
keywords:
  - amr
  - fasta
  - sccmec
  - staphylococcus
tools:
  - sccmec:
      description: A tool for typing SCCmec cassettes in assemblies.
      homepage: https://github.com/rpetit3/sccmec
      documentation: https://github.com/rpetit3/sccmec
      tool_dev_url: https://github.com/rpetit3/sccmec
      licence: ["MIT"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: FASTA assembly file
        pattern: "*.{fasta,fasta.gz,fa,fa.gz,fna,fna.gz}"
        ontologies: []
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.tsv":
          type: file
          description: |
            Tab-delimited results. Includes five files:
            {prefix}.tsv (final typing result),
            {prefix}.targets.details.tsv,
            {prefix}.targets.blastn.tsv,
            {prefix}.regions.details.tsv,
            {prefix}.regions.blastn.tsv
          pattern: "*.{tsv}"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@rpetit3"
maintainers:
  - "@rpetit3"
